### ISSUE TITLE
Coverage reporting to codecov.io

### ISSUE THREAD

**Issue by ErikBjare** [uniswap-python/uniswap-python#109]
I use codecov.io for other projects, and it's really helpful to see how PRs change your test coverage (like this: https://github.com/ActivityWatch/aw-core/pull/94#issuecomment-667932464). We already have code coverage set up, it just isn't being reported.

@shanefontaine: Could you enable codecov.io on the repo? (I can add the CI config needed) 

But now that I think about it: perhaps it'd be ideal to move the repo to a uniswap-python org, where the repo can have more than one owner, so I can do stuff like this myself.

**Comment by shanefontaine** [comment]
> perhaps it'd be ideal to move the repo to a uniswap-python org

I think that is the right call. The repo has been transferred to a new org. Please confirm that you are able to add coverage reporting and close this issue when it has been completed!

**Comment by ErikBjare** [comment]
Nice, thanks!

Coverage reporting added in https://github.com/uniswap-python/uniswap-python/commit/f0719fd3cf0e47eb0ec941c1faaee9dd5037d8c4. Also added a badge to the README.

Results viewable here: https://app.codecov.io/gh/uniswap-python/uniswap-python
