### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by victorsemeraro** [uniswap-python/uniswap-python#117]
Hello, 

I am new to the Uniswap Api. I am just trying to initialize the uniswap class from the tutorial, but I get this error:

"HTTPError: 401 Client Error: Unauthorized for url: https://mainnet.infura.io/v3/..."

The code is below

`
import uniswap as uni

# PARAMETERS
wallet_address = '0xA7091C5076b8Aa6f9aa7bdCFd810d96735ea9e2a'
private_key = '...'
version = 3
web3_provider = 'https://mainnet.infura.io/v3/...'

# UNISWAP CLASS INTERFACE
def uniswap(arg1, arg2, arg3, arg4):
    
    uni_class = uni.Uniswap(address = arg1, private_key = arg2, version = arg3, 
                            provider = arg4)
    
    return uni_class

# CALL FUNCTION
uniswap(wallet_address, private_key, version, web3_provider)
`

**Comment by ErikBjare** [comment]
You need a proper `web3_provider` URL, the one in the tutorial is just a placeholder (as indicated by the `...`). You can get one from infura.io.

And you probably don't want to leave your `private_key` in a comment like that... (which is also on the wrong format, you need to derive the private key from your seed phrase).
