### ISSUE TITLE
API docs have SAI address instead of DAI in an example

### ISSUE THREAD

**Issue by mzmyslowski** [uniswap-python/uniswap-python#125]
The code in the following section https://uniswap-python.com/getting-started.html#initializing-the-uniswap-class has the variable "dai" that has the SAI address assigned. I thought that I had something wrong with the decimal conversion but I was just quoting different tokens pair.

**Comment by manawenuz** [comment]
please fix it, it wasted 10 minutes of my time, trying to figure out what is wrong
