### ISSUE TITLE
Error with quickswap

### ISSUE THREAD

**Issue by PeterLeeFS** [uniswap-python/uniswap-python#131]
Tried the following code on quickswap and got error with the last line: "web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'int'>, <class 'str'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types."
Not sure I'm doing it right...

`MaticRPC = "https://rpc-mainnet.matic.network"
router_contract_addr  = "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
factory_contract_addr = "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"
pair_contract_addr = "0xadbF1854e5883eB8aa7BAf50705338739e558E5b"
quickswap = Uniswap(address=None, private_key=None, version=2,
                    factory_contract_addr=factory_contract_addr,
                    router_contract_addr=router_contract_addr, provider=MaticRPC)

weth = "0xCD3882232E36ad188968BCC4dbC742c14d6A6B21"
quick = "0x831753DD7087CaC61aB5644b308642cc1c33Dc13"

eth_quick = quickswap.get_price_input(weth, quick, 1,route="0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270")`

**Comment by liquid-8** [comment]
ETH contract on matic is 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619 afaik

also if you mean "1ETH for Xquick" then
```
qty = 1*10**quickswap.get_token(weth).decimals
eth_quick = quickswap.get_price_input(weth, quick, qty, route=[weth,quick])
```

**Comment by PeterLeeFS** [comment]
> ETH contract on matic is 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619 afaik
> 
> also if you mean "1ETH for Xquick" then
> 
> ```
> qty = 1*10**quickswap.get_token(weth).decimals
> eth_quick = quickswap.get_price_input(weth, quick, qty, route=[weth,quick])
> ```

Thanks a lot! I picked the wrong weth address and got confused with the route. It works now.
