### ISSUE TITLE
No route specified, assuming route...

### ISSUE THREAD

**Issue by HYSWZW** [uniswap-python/uniswap-python#141]
run:
`web3 = ini_provider(bsc_wss)
pancake = Uniswap(address=address, private_key=private_key, version=version, web3=web3, default_slippage=0.3, router_contract_addr=pan_router)
tx = sell_token(busd, mint, 300000)`
result:
`No route specified, assuming route: ['0x1f3Af095CDa17d63cad238358837321e95FC5915', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c', '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56']
0x9aa3e852bfd743502b31a32b747bac658bcc9cb9ea8fc0832d925a9a8482cfc7`
but i have added router_contract_addr,and successful transaction,why does it still appear: **No route specified, assuming route**
plz,help

**Comment by liquid-8** [comment]
Well, this message is just "for your information". Your `sell_token()` function calls `make_trade()` or `make_trade_output()`. These methods call pricing methods i.e. `_get_token_token_input_price()` for a reason. Pricing methods have optional parameter `route`. If this param is omitted then **"No route specified"** message is been shown.

**Comment by HYSWZW** [comment]
thx for you help
