### ISSUE TITLE
Can't quote price

### ISSUE THREAD

**Issue by ericmsott** [uniswap-python/uniswap-python#149]
I'm trying o use the function 'get_price_input', but it is raising the following error:

`    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `quoteExactInputSingle`, positional argument(s) of type `(<class 'str'>, <class 'str'>, <class 'int'>, <class 'float'>, <class 'int'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `quoteExactInputSingle`: ['quoteExactInputSingle(address,address,uint24,uint256,uint160)']
Function invocation failed due to no matching argument types.`

**Comment by sweeta20793** [comment]
Hey, try to use int(value) to resolve.
