### ISSUE TITLE
Help with BSC trade

### ISSUE THREAD

**Issue by gn3sh** [uniswap-python/uniswap-python#166]
I am trying to make a trade through Pancake Swap.
I added constants as described [here](https://githubmemory.com/repo/uniswap-python/uniswap-python/issues/126) 

And this is my code:
`from uniswap import Uniswap
from web3 import Web3

address = xxx
private_key = xxx
version = 2

bsc = "https://bsc-dataseed.binance.org/"

web3 = Web3(Web3.HTTPProvider(bsc))
print(web3.isConnected())
uniswap = Uniswap(address=address, private_key=private_key, version=version, web3=web3, default_slippage=0.01)

wbnb = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
token = "0xacd7b3d9c10e97d0efa418903c0c7669e702e4c0"

wbnb_w = Web3.toChecksumAddress(wbnb)
token_w = Web3.toChecksumAddress(token)

qty = int(.001 * 10**18)

uniswap.make_trade(wbnb_w, token_w, qty)
`

And this is transaction
https://bscscan.com/tx/0x893559bb3e3e8c83fbb2fa66c8944d6ec6aafd807842fbcbaf9ffa3e4270ac44 

Please help me to get it working.

**Comment by liquid-8** [comment]
Everything seems to be OK regarding  code but i suppose that slippage is too low. Try to set `default_slippage=0.05` or even more because BSC prices are highly volatile AFAIK.

**Comment by gn3sh** [comment]
I am trying to do it, but now get an error

>  Insufficient balance. Had 0, needed 1000000000000000

If I am trying to get BNB balance from my wallet:
```
qty_token = uniswap.get_token_balance(wbnb)
print(qty_token)
```
output is 0, but I have positive balance of BNB

What am I doing wrong?

**Comment by gn3sh** [comment]
Please tell me If the following code is equivalent to previous?

address = ***
private_key ***

version = 2                       # specify which version of Uniswap to use
provider = "https://mainnet.infura.io/v3/c4de25213bd342ed97074ea3415175e8"    # can also be set through the environment variable `PROVIDER`
# provider = "wss://bsc-ws-node.nariox.org:443"
bsc = "https://bsc-dataseed.binance.org/"

# uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, default_slippage=0.01)
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=bsc, default_slippage=0.05)

# Some token addresses we'll be using later in this guide
eth = "0x0000000000000000000000000000000000000000"
bnb = "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c"
bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
dai = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
ftm = "0x4E15361FD6b4BB609Fa63C81A2be19d873717870"
gala_eth = "0x15D4c048F83bd7e37d49eA4C83a07267Ec4203dA"
gala_bsc = "0x7ddee176f665cd201f93eede625770e2fd911990"
ele = "0xacd7b3d9c10e97d0efa418903c0c7669e702e4c0"
woo = "0x4691937a7508860f876c9c0a2a617e7d9e945d4b"

qty =  int(0.001*10**18)
uniswap.make_trade(bnb, gala_bsc, qty)

**Comment by gn3sh** [comment]
I can't get it working. 
I tried slippage 0.05, but result was the same. 
After all now I have an error: 

> uniswap.exceptions.InsufficientBalance: Insufficient balance. Had 0, needed 1000000000000000

But I have BNB balance in my wallet.

Also can you please advice Is code below is equivalent to the code which i posted before?:

```
from uniswap import Uniswap

address = xxx
private_key = xxx
version = 2

provider = "https://bsc-dataseed.binance.org/"

uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, default_slippage=0.05)

wbnb = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
token = "0xacd7b3d9c10e97d0efa418903c0c7669e702e4c0"

qty = int(0.001*10**18)
uniswap.make_trade(wbnb, token, qty)
```

Thank you for helping. I really appreciate it.

**Comment by liquid-8** [comment]
> Is code below is equivalent to the code which i posted before?

Yes, it is. Btw you don't have to add constants manually bc that issue had been fixed:
https://github.com/uniswap-python/uniswap-python/issues/126
Actually, I'd rather recommend to remove this code.

Regarding your question: try ETH_ADDRESS constant instead of BNB's contract OR you might wrap some BNB before swap via pancakeswap web-app/whatever you like if you need to use BNB contract exactly.

**Comment by gn3sh** [comment]
Thank you!! It worked.
But changing ETH_ADDRESS in package code will result that i can't make trades on both networks.
Is there any easy way to have two parameters depending on the provider?
Thanks again!

**Comment by gn3sh** [comment]
Wrapping BNB before swap and making trade (without changing ETH_ADDRESS) resulted IDENTICAL_ADDRESSES error.

**Comment by liquid-8** [comment]
> changing ETH_ADDRESS
Can't understand. What contract exactly did you put there?

**Comment by gn3sh** [comment]
First i tried to wrap bnb so that i have WBNB balance and run the [previous](https://github.com/uniswap-python/uniswap-python/issues/166#issuecomment-922344671) code. Transaction failed with error: IDENTICAL_ADDRESSES

Second i tried to change constant ETH_ADDRESS to WBNB contract and it worked.

But with this parameter set to WBNB i can't make UNISWAP trades? I'd like to make both trades - Pancake and Uniswap.

**Comment by liquid-8** [comment]
no, just put old value there and then try

`uniswap.make_trade(ETH_ADDRESS, token, qty)`

**Comment by gn3sh** [comment]
Not working ;(  

Transaction - https://bscscan.com/tx/0x7ad680a35352b67e2214426db7fe11b1bd5eef7e7faa47555cbdc597f677443e

constants.py:
`ETH_ADDRESS = "0x0000000000000000000000000000000000000000"`

code:
```
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, default_slippage=0.05)

eth = "0x0000000000000000000000000000000000000000"
bnb = Web3.toChecksumAddress("0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c")
ele = Web3.toChecksumAddress("0xacd7b3d9c10e97d0efa418903c0c7669e702e4c0")

qty = int(0.001*10**18)
uniswap.make_trade(bnb, ele, qty)

```

**Comment by liquid-8** [comment]
last line shoud be

> uniswap.make_trade(ETH_ADDRESS, ele, qty)

or

> uniswap.make_trade(eth, ele, qty)
if you like

**Comment by liquid-8** [comment]
grats!

**Comment by gn3sh** [comment]
Thank you!!!
Everything is working!

**Comment by King338gacor** [comment]
Pragmatic Play adalah salah satu penyedia game online terbaik yang sangat populer di Asia, terutama di Indonesia. Dengan berbagai pilihan permainan menarik seperti Wild Wild West, Zeus Game, Sweet Bonanza, FAFA, Aztec Gems, dan Gate of Olympus, Pragmatic Play menawarkan pengalaman bermain yang seru dan menghibur. Selain itu, mereka juga menyediakan demo gratis untuk mencoba permainan sebelum menggunakan uang asli. Hal ini menjadikan Pragmatic Play sebagai pilihan utama bagi para penggemar game online, terutama dengan hadiah jackpot besar hingga ratusan juta rupiah.
[url=https://https://176.97.117.132]king338[/url]
[url=https://casinoworlds.net]king338[/url]
[url=https://beritaterbaru.net]king338[/url]
