### ISSUE TITLE
Support EIP-1559

### ISSUE THREAD

**Issue by WCG2021** [uniswap-python/uniswap-python#169]
Hello author, after several days of exploration, I finally learned how to use this source code, great code! But it seems that it does not support EIP-1559 on the issue of GAS. For me as a rookie, I don’t know how to modify it. Can you update the gas cost of EIP-1559?
![@(2Y`M`XXDJF`8OVE1` EG3](https://user-images.githubusercontent.com/91224141/134476937-40b3743e-8d14-4da4-8c8a-aebc15c7cfd4.png)
![1`BVT _4ZA UXP`7I(}@`FX](https://user-images.githubusercontent.com/91224141/134477216-b292a7a4-4405-46af-bb6b-3f980cb6a2b9.png)

**Comment by WCG2021** [comment]
poetry update web3

**Comment by WCG2021** [comment]
The version of Web3 is 5.19.0, so eip1559 is not supported
only need to upgrade the Web3 file, and finally in get_ tx_ Added in params
"maxFeePerGas": 12000000000,
"maxPriorityFeePerGas": 11000000000,
"type": 0x2,
You can use eip1559 directly

poetry update web3

**Comment by ErikBjare** [comment]
@WCG2021 Reopening in case anyone wants to upstream your suggestions.

**Comment by liquid-8** [comment]
BSC doesn't support EIP-1559 at the moment as far as I know. On eth mainnet/testnets you may use the new format only.

**Comment by ErikBjare** [comment]
Pretty sure this has been fixed, closing.
