### ISSUE TITLE
incredible swap (i lost 13,9k usdt)

### ISSUE THREAD

**Issue by speriamoBene** [uniswap-python/uniswap-python#196]
Hello, i did a swap a little while ago and inexplicably lost 13,900 usdt

i just used the instruction 

uniswap.make_trade(usdt, symbolUniswap, 13900 * 1000000)

where:
usdt = Web3.toChecksumAddress("0xdac17f958d2ee523a2206206994597c13d831ec7")
symbolUniswap = Web3.toChecksumAddress("0x7d29a64504629172a429e64183d6673b9dacbfce")

But i only received the equialent of 17 usdt instead of 13,9k.
How is it possible?

**Comment by ErikBjare** [comment]
Duplicate of #198, closing.
