### ISSUE TITLE
when i was using ropsten,it comes out with UniswapV2Library: INSUFFICIENT_LIQUIDITY

### ISSUE THREAD

**Issue by FILAgiao** [uniswap-python/uniswap-python#203]
when i want to trade eth to bat,because of the high price of gas in the main net,i had to use the Ropsten.
i can trade with ropsten in uniswap'website ,but in your code,it comes out with the error:**UniswapV2Library: INSUFFICIENT_LIQUIDITY**
i don't know why.
sincerely need your help.
yours easygirl.th

**Comment by FILAgiao** [comment]
i can also check the price at main net,i am using v2, v1/v3 has problem too

**Comment by liquid-8** [comment]
Hi!
I'm not sure if I understand your purposes right. If you consider using testnets like Ropsten for development/tests then look at this thread
https://github.com/uniswap-python/uniswap-python/discussions/151
Otherwise, please provide more information.

**Comment by FILAgiao** [comment]
> Hi!
> 
> I'm not sure if I understand your purposes right. If you consider using testnets like Ropsten for development/tests then look at this thread
> 
> https://github.com/uniswap-python/uniswap-python/discussions/151
> 
> Otherwise, please provide more information.

Ooze, I see. I was using DAI and BAT to swap. Seems they has different contract addresses in Ropsten instead of the mainnet. Thank u my man.
