### ISSUE TITLE
AttributeError: 'Uniswap' object has no attribute 'approve'

### ISSUE THREAD

**Issue by starascendin** [uniswap-python/uniswap-python#204]
Does anyone get this issue `AttributeError: 'Uniswap' object has no attribute 'approve'? 

I looked around and it seemed to be here https://github.com/uniswap-python/uniswap-python/blob/master/uniswap/decorators.py#L29 and i don't find any reference to any method with `.approve`.

**Comment by liquid-8** [comment]
Post your code plz

**Comment by ErikBjare** [comment]
Closing since there's no reply, and no info to go on.
