### ISSUE TITLE
The .get_price_input() and how can I check the liquidity before i make auto trade?

### ISSUE THREAD

**Issue by FILAgiao** [uniswap-python/uniswap-python#209]
```
uniswap_wrapper = Uniswap(address, private_key=None, version=3, provider=eth_provider)
eth = "0x0000000000000000000000000000000000000000"
bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
dai = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
alcx=Web3.toChecksumAddress('0xdbdb4d16eda451d0503b854cf79d55697f90c8df')
address = "0x0000000000000000000000000000000000000000"
```

### when i want to use the Uniswap.get_price_input()
when i am try ing to`sup_price = uniswap_wrapper.get_price_input(eth,dai,1*10**18)`,i can get the proper price
### but when i replace the eth with alcx ,exception raise up with:

> File "D:\py39\lib\site-packages\uniswap\uniswap.py", line 178, in get_price_input
>     return self._get_token_token_input_price(token0, token1, qty, fee, route)
>   File "D:\py39\lib\site-packages\uniswap\uniswap.py", line 276, in _get_token_token_input_price
>     price = self.quoter.functions.quoteExactInputSingle(
>   File "D:\py39\lib\site-packages\web3\contract.py", line 959, in call
>     return call_contract_function(
>   File "D:\py39\lib\site-packages\web3\contract.py", line 1503, in call_contract_function
>     return_data = web3.eth.call(
>   File "D:\py39\lib\site-packages\web3\module.py", line 57, in caller
>     result = w3.manager.request_blocking(method_str,
>   File "D:\py39\lib\site-packages\web3\manager.py", line 187, in request_blocking
>     return self.formatted_response(response,
>   File "D:\py39\lib\site-packages\web3\manager.py", line 167, in formatted_response
>     apply_error_formatters(error_formatters, response)
>   File "D:\py39\lib\site-packages\web3\manager.py", line 67, in apply_error_formatters
>     formatted_resp = pipe(response, error_formatters)
>   File "cytoolz\functoolz.pyx", line 667, in cytoolz.functoolz.pipe
>   File "cytoolz\functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
>   File "D:\py39\lib\site-packages\web3\_utils\method_formatters.py", line 573, in raise_solidity_error_on_revert
>     raise ContractLogicError('execution reverted')
> web3.exceptions.ContractLogicError: execution reverted
**_### why?_**
### Does it me i can only get parity price at this function?How can I check the liquidity before i make auto trade?

**Comment by liquid-8** [comment]
There is no DAI-ALCX pool on Uniswap3. At the moment, only direct pools are supported for it. In this particular case, the swap route is DAI-ETH-ALCX.

**Comment by FILAgiao** [comment]
OK，thanks. @liquid-8
