### ISSUE TITLE
raise_solidity_error_on_revert

### ISSUE THREAD

**Issue by ruhrohroh** [uniswap-python/uniswap-python#213]
File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 580, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')
web3.exceptions.ContractLogicError: execution reverted
Getting hit when I use uniswap.make_trade(***)

**Comment by liquid-8** [comment]
I think it is a good idea to search for your error code before creating an issue.

**Comment by ErikBjare** [comment]
Should have searched other issues first, and not enough info to resolve anyway. Closing.
