### ISSUE TITLE
Could you provide an API for get all the timely transaction record on the uniswap about  some two token.

### ISSUE THREAD

**Issue by CnBDM-Su** [uniswap-python/uniswap-python#215]
As the title says could you provide an API for get all the timely transaction record on the uniswap about  some two token.
Thanks

**Comment by liquid-8** [comment]
First of all, remove the "bug" label, please.
In general, it is possible, though I'm not sure about performance considering it is Python. Also, features like this one aren't at the top of the to-do list definitely.
