### ISSUE TITLE
Slippage not working properly?

### ISSUE THREAD

**Issue by jornx** [uniswap-python/uniswap-python#226]
Hi!
I am trying to make a trade on Sushiswap Polygon, but I keep getting sandwiched. 

`sushipoly = Uniswap(address=wallet, private_key=walletkey, provider=provider['polygon'], version=2, default_slippage=0.002, web3=w3['polygon'], factory_contract_addr=sushi['polygon']['factory'], router_contract_addr=sushi['polygon']['router'])
tx = swap.make_trade(Web3.toChecksumAddress(weth), Web3.toChecksumAddress(contactaddress), int(amount * (10 ** decimals)), slippage=0.002)
`

This is my code. 
I made one change in the library to be able to swap straight from WETH to the coin I'm buying and not through Matic, but that should not have any impact on the slippage I would think.
Anyone know what I'm doing wrong?

**Comment by mmm3bbb** [comment]
Did u resolve this? I am having the same problem with uniswap v3. It's calling this:
`
            price = self.quoter.functions.quoteExactInputSingle(
                token0, token1, fee, qty, sqrtPriceLimitX96
            ).call()
`          
with sqrtPriceLimitX96 hard-coded to 0 and then multiplying this by (1 - slippage)

Whatever the number is doesn't appear to be correct as I just got mercilessly sandwiched with slippage==0.01.

**Comment by mmm3bbb** [comment]
Hmmm, the output of quoteExactInputSingle matches what the Uniswap UI shows, so I guess there's nothing wrong with the function.
