### ISSUE TITLE
what is WEB3 PROVIDER URL?

### ISSUE THREAD

**Issue by a5601564** [uniswap-python/uniswap-python#228]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Ideally, you can provide a code example demonstrating the issue (including the Uniswap version, tokens/route, and network used).

**Expected behavior**

**Additional context**
Add any other context about the problem here, such as a transaction ID demonstrating the problem.

i can't firgue it out.

**Comment by a5601564** [comment]
infura.io ???

**Comment by ErikBjare** [comment]
The PROVIDER needs to be set to the URL of an Ethereum node.

Either you run a node yourself, or you can register on Infura and use that.
