### ISSUE TITLE
Compatibility issues with ganache v7.0.1

### ISSUE THREAD

**Issue by RaRedmer** [uniswap-python/uniswap-python#232]
**Bug description**

The test at `tests/test_uniswap.py::TestUniswap::test_get_fee_maker[1]` always results in an error due to refusal to establish a connection with the local target machine:

```
During handling of the above exception, another exception occurred:
E   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001873E1940A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
```

While trying to pinpoint the exact error, I noticed that the option `--miner.legacyInstamine true` was not available for my ganache version v7.0.1

**Reproduction**

Setup:
- Windows 10
- ganache v7.0.1

Run `make test` 

**Solution Proposal**

Replace `--miner.legacyInstamine true` with either `--miner.instamine "eager"` or `--miner.instamine "strict"` in  `tests/test_uniswap.py`
```
p = subprocess.Popen(
        f"""ganache
        --port {port}
        --wallet.seed test
        --chain.networkId 1
        --chain.chainId 1
        --fork.url {os.environ['PROVIDER']}
        --miner.defaultGasPrice {defaultGasPrice}
        --miner.instamine "eager"
        """.replace(
            "\n", " "
        ),
        shell=True,
    )
```

**Comment by ErikBjare** [comment]
Thanks for looking into this! I've made a PR in #233 and included you as a coauthor.
