### ISSUE TITLE
use_estimate_gas - the parameters have no effect

### ISSUE THREAD

**Issue by venom-d** [uniswap-python/uniswap-python#242]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Ideally, you can provide a code example demonstrating the issue (including the Uniswap version, tokens/route, and network used).

**Expected behavior**

**Additional context**
Add any other context about the problem here, such as a transaction ID demonstrating the problem.

**Comment by ErikBjare** [comment]
Not true, see: https://github.com/uniswap-python/uniswap-python/blob/29b3e7226327dca5cd28c1f79c51f0ff5c458e9b/uniswap/uniswap.py#L1110
