### ISSUE TITLE
cannot import name 'Uniswap'

### ISSUE THREAD

**Issue by fedorzh** [uniswap-python/uniswap-python#244]
**Describe the bug**
Installed on SageMaker machine in conda_python3 environment, using `pip install uniswap-python`, getting `ImportError: cannot import name 'Uniswap'` after kernel restart as well

**To Reproduce**
see above

**Expected behavior**
Everything works

**Additional context**

**Comment by ErikBjare** [comment]
There's nothing to go on here.

I just did the following, which works fine:

```
python3 -m temp_venv
source temp_venv/bin/activate
pip install uniswap-python
python3 -c "from uniswap import Uniswap; print(Uniswap)"
```

Can you provide a full example?

**Comment by fedorzh** [comment]
Here is the full screenshot of a SageMaker EC2 notebook output
![image](https://user-images.githubusercontent.com/5185993/159859874-700e778d-2677-464f-8340-d71e8a8478b7.png)

**Comment by fedorzh** [comment]
There is absolutely nothing specific about this setup, just create a SageMaker notebook with the instance ml.t3.medium though I am sure it's the same for other instances

**Comment by fedorzh** [comment]
(of course, the commented out cell has been previously successfully run)

**Comment by fedorzh** [comment]
Ok this happens because SageMaker has python 3.6 and you support only 3.7+, so feel free to close the issue of you don't feel like fixing this is needed for you
