### ISSUE TITLE
With ganache-cli and mainnet-fork got 'Method eth_maxPriorityFeePerGas not supported.' error

### ISSUE THREAD

**Issue by madpower2000** [uniswap-python/uniswap-python#247]
With Ganache CLI v6.12.2 and mainnet-fork got error :

 ` 'Method eth_maxPriorityFeePerGas not supported.'`

on make_trade() call.

**Comment by ErikBjare** [comment]
You need to use Ganache CLI v7, as v6 doesn't support EIP-1559 transactions.
