### ISSUE TITLE
Are there any tutorials on how to easily start trading using Uniswap Python?

### ISSUE THREAD

**Issue by bitcoinmeetups** [uniswap-python/uniswap-python#250]
Hello,

I'm BM. A very nice and polite guy.

Are there any tutorials on how to easily start trading using Uniswap Python? I would like to be able to swap DAI for WETH using uniswap-python for example.

**Comment by ErikBjare** [comment]
There's documentation doing just that linked in the README.

Please read/skim http://www.catb.org/~esr/faqs/smart-questions.html before asking further questions.
