### ISSUE TITLE
Could not identify the intended function with name `quoteExactOutputSingle`

### ISSUE THREAD

**Issue by 1byari** [uniswap-python/uniswap-python#255]
Hi! I tried to exchange ETH for USDC, but I keep getting this error:

web3.exceptions.ValidationError:
Could not identify the intended function with name `quoteExactOutputSingle`, positional argument(s) of type `(<class 'str'>, <class 'str'>, <class 'int'>, <class 'float'>, <class 'int'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `quoteExactOutputSingle`: ['quoteExactOutputSingle(address,address,uint24,uint256,uint160)']
Function invocation failed due to no matching argument types.

from uniswap import Uniswap
address = "0x"     
private_key = ""  
version = 3                 
provider = "https://optimism-mainnet.infura.io/v3/"
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider)

eth = "0x0000000000000000000000000000000000000000"
usdc = '0x7F5c764cBc14f9669B88837ca1490cCa17c31607'

tx = uniswap.make_trade_output(eth,usdc, 0.0003743)
print(tx)

**Comment by ErikBjare** [comment]
You're passing a float as the amount. Don't do that. Read the docs.
