### ISSUE TITLE
Uniswap import error on Linux

### ISSUE THREAD

**Issue by Haavi97** [uniswap-python/uniswap-python#275]
**Describe the bug**
I get the same error every time I try to import Uniswap on Linux:
```ImportError: cannot import name 'Uniswap' from 'uniswap' (/home/pi/project_name/venv/lib/python3.9/site-packages/uniswap/__init__.py)```

**To Reproduce**
1. I install my dependencies in a virtual environment using venv and 
2. In my main script I try to import Uniswap by ```from uniswap import Uniswap``` and gives the same error as in the description of the bug.

```pip freeze``` output:
```
attrdict==2.0.1
certifi==2022.9.24
charset-normalizer==2.1.1
contourpy==1.0.5
cycler==0.11.0
cytoolz==0.12.0
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.5.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.9.5
fonttools==4.37.3
hexbytes==0.3.0
idna==3.4
kiwisolver==1.4.4
lru-dict==1.1.8
matplotlib==3.6.0
numpy==1.23.3
packaging==21.3
parsimonious==0.8.1
Pillow==9.2.0
py-solc==3.2.0
pycryptodome==3.15.0
pyparsing==3.0.9
python-dateutil==2.8.2
python-dotenv==0.21.0
requests==2.28.1
rlp==2.0.1
semantic-version==2.10.0
six==1.16.0
toolz==0.12.0
uniswap-python==0.3.4
urllib3==1.26.12
web3==4.7.2
websockets==6.0
```

**Expected behavior**
The expected behaviour would be to use the Uniswap class as in the docs :) and as it smoothly works on Windows.

**Additional context**
Add any other context about the problem here, such as a transaction ID demonstrating the problem.

**Comment by ErikBjare** [comment]
Just a guess: Do you perhaps have a file or folder called `uniswap` in your python path?

**Comment by Haavi97** [comment]
I double checked and now. 
running
```python -c "import sys; print(sys.path)"```
I get the following:
```
['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/pi/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.9/dist-packages']
```

Actually I'm running it in a virtual environment with a fresh directory and actually totally clean machine. I just booted new and installed the dependencies in venv. The import error points to: ```home/pi/project_name/venv/lib/python3.9/site-packages/uniswap```

**Comment by Haavi97** [comment]
@ErikBjare if you mean in the directoy where the script is executed then also no. There is no file or folder called uniswap.
And doesn't matter from with path I try to import uniswap it gives the same import error.

Seems that the installing in Linux is not working well. Running in the Python shell help(uniswap) (I can import uniswap as library) gives the following output which seems totally empty, as it is checking he files in the directory where they are suposedely succefully installed:

**Comment by ErikBjare** [comment]
Just installed it locally myself (macOS today) and it works fine:

```
Help on package uniswap:

NAME
    uniswap

PACKAGE CONTENTS
    cli
    constants
    decorators
    exceptions
    token
    tokens
    types
    uniswap
    util

DATA
    main = <Group main>

FILE
    /Users/erb/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uniswap/__init__.py
```

How does your `/home/pi/project_name/venv/lib/python3.9/site-packages/uniswap/` look?

**Comment by ErikBjare** [comment]
lol, I notice now that your `pip freeze` shows uniswap-python v0.3.4?! You should probably bump that to v0.6

**Comment by ErikBjare** [comment]
Maybe because it was impossible to fulfill a version constraint, like we might depend on a newer web3 or something, but didn't back for 0.3.4.
