### ISSUE TITLE
KeyError: 100 when trying to get bitmap spacing for 0.01% pool

### ISSUE THREAD

**Issue by IanMichaelHarper** [uniswap-python/uniswap-python#277]
I feel there should be an element for 100 [here](https://github.com/uniswap-python/uniswap-python/blob/ff26afbab70226d782f2e74557f2139a25c9afa2/uniswap/constants.py#L69) yielding the correct values. 

This is a breaking change for me when working with 0.01% pools

**Comment by KeremP** [comment]
Ah, good catch - had forgotten that other fee tiers had been added besides the original three when writing the tickBitMap logic. I should be able to add this later today and make a PR.

Also I should probably document how these ranges are calculated for the future.
