### ISSUE TITLE
The data obtained by function “get_price_input” is inaccurate

### ISSUE THREAD

**Issue by shankshaw** [uniswap-python/uniswap-python#282]
**Describe the bug**
Here is my code：
——————————————
from uniswap import Uniswap
from web3 import Web3
true = True
false = False

eth = Web3.toChecksumAddress("0x0000000000000000000000000000000000000000")
weth = Web3.toChecksumAddress("0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6")
usdc = Web3.toChecksumAddress("0xD87Ba7A50B2E7E660f678A895E4B72E7CB4CCd9C")
wbtc = Web3.toChecksumAddress("0xC04B0d3107736C32e19F1c62b2aF67BE61d63a05")

address = "" 
private_key = ""

provider = "https://goerli.infura.io/v3/"
uniswap_wrapper = Uniswap(address, private_key, version=3, provider=provider) 

eth_unit = uniswap_wrapper.get_token(weth).decimals
usdc_unit = uniswap_wrapper.get_token(usdc).decimals
eth_amount1 = uniswap_wrapper.get_token_balance(weth)/10 ** eth_unit
usdc_amount1 = uniswap_wrapper.get_token_balance(usdc)/10 ** usdc_unit
print("eth_amount1 ", eth_amount1 )
print("usdc_amount1 ", usdc_amount1)
eth_price = uniswap_wrapper.get_price_input(weth, usdc, 10 ** 18, 500)/10 ** usdc_unit
print("eth_price", eth_price)
uniswap_wrapper.make_trade(weth, usdc, 10 ** 16, fee=500)
time.sleep(60)
eth_amount2 = uniswap_wrapper.get_token_balance(weth)/10 ** eth_unit
usdc_amount2 = uniswap_wrapper.get_token_balance(usdc)/10 ** usdc_unit
print("eth_amount2 ", eth_amount2 )
print("usdc_amount2 ", usdc_amount2 )

print("actual price", (usdc_amount2 -usdc_amount1)/0.01)
______________________________
i get the output:
eth_amount1  0.028
usdc_amount1  120703.095604
eth_price 663899.448307
eth_amount2  0.018
usdc_amount2  134488.875334
actual price 1378577.973000001

**Expected behavior**
The eth_price obtained by function “get_price_input” is inconsistent with the“actual price” in the transaction.In fact, this still happens when fee=3000 and 10000.
I am using the goerli testnet.

**Comment by liquid-8** [comment]
Not a bug. Testnet v3 pools have little liquidity. Therefore, the price impact might be severe. Run the same code on the mainnet to ensure it works as intended. Also, you can't get the spot price this way. Should use `get_raw_price(...)` for that. Check the code out if you need an explanation of why.

**Comment by shankshaw** [comment]
> Not a bug. Testnet v3 pools have little liquidity. Therefore, the price impact might be severe. Run the same code on the mainnet to ensure it works as intended. Also, you can't get the spot price this way. Should use `get_raw_price(...)` for that. Check the code out if you need an explanation of why.

I understand, thank you very much for your answer.
