### ISSUE TITLE
Help Wanted: close_position function

### ISSUE THREAD

**Issue by avasque2** [uniswap-python/uniswap-python#288]
I am looking for someone who can provide the py file or snippet of code that successfully executes the close_position function. I believe it is a bug but I am a noob, so might not be implementing it correctly.

.05 ETH reward just drop your wallet address.

**Comment by ErikBjare** [comment]
You haven't provided any information about your issue, please read: http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by avasque2** [comment]
Sorry this wasn't meant to be a question or an issue. I didn't see the option to tag it as a request/non-issue. I am not interested in spending more time trying to figure out what I am doing wrong and am requesting someone to provide a working script that I can learn from and for this I would compensate them .05 ETH. If this doesn't belong here then feel free to close/delete this post. Thank you.
