### ISSUE TITLE
Close_position on Optimism

### ISSUE THREAD

**Issue by avasque2** [uniswap-python/uniswap-python#295]
I get the following error on the _close_position_ function call:

_web3.exceptions.ExtraDataLengthError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes_

I assume this wrapper works on Optimism as I have no problems getting liquidity positions and token balance.
Below is the code.

```
from uniswap import Uniswap

TOKEN_ID = 240756

address = WALLET_ADDRESS       
private_key = PRIVATE_KEY
version = 3                       
provider = "https://optimism-mainnet.infura.io/v3/13b22632db5c4248bd6f5942d82e248d"   
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider)

op = "0x4200000000000000000000000000000000000042"
usdc = "0x7f5c764cbc14f9669b88837ca1490cca17c31607"

ONE_ETH = 1 * 10 ** 18
ONE_USDC = 1 * 10 ** 6

print('Eth balance in metamask = '+str(uniswap.get_liquidity_positions()))
print('OP balance in metamask = '+str(uniswap.get_token_balance(op)/ONE_ETH))
print('USDC balance in metamask = '+str(uniswap.get_token_balance(usdc)/ONE_USDC))

tx = uniswap.close_position(TOKEN_ID)
print(tx)
```

**Comment by liquid-8** [comment]
Try to add
```
w3 = Web3(HTTPProvider(provider))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, web3=w3)
```
Should work.

**Comment by avasque2** [comment]
Thanks @liquid-8 that definitely helped and I got further.  Now I have the following error which I think is unrelated: 

> ValueError: {'code': -32601, 'message': 'The method eth_sendTransaction does not exist/is not available'}

**Comment by avasque2** [comment]
Original question was answered so I'll close this and start a new thread thanks again @liquid-8
