### ISSUE TITLE
The method eth_sendTransaction does not exist/is not available error when close_position on optimism

### ISSUE THREAD

**Issue by avasque2** [uniswap-python/uniswap-python#297]
I get the following error on the close_position function call:

> ValueError: {'code': -32601, 'message': 'The method eth_sendTransaction does not exist/is not available'}

Here is the code:

from uniswap import Uniswap

TOKEN_ID = 240756

address = WALLET_ADDRESS       
private_key = PRIVATE_KEY
version = 3                       
provider = "https://optimism-mainnet.infura.io/v3/13b22632db5c4248bd6f5942d82e248d"

w3 = web3.Web3(web3.HTTPProvider(provider))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, web3= w3)

op = "0x4200000000000000000000000000000000000042"
usdc = "0x7f5c764cbc14f9669b88837ca1490cca17c31607"

ONE_ETH = 1 * 10 ** 18
ONE_USDC = 1 * 10 ** 6

print('Eth balance in metamask = '+str(uniswap.get_liquidity_positions()))
print('OP balance in metamask = '+str(uniswap.get_token_balance(op)/ONE_ETH))
print('USDC balance in metamask = '+str(uniswap.get_token_balance(usdc)/ONE_USDC))

tx = uniswap.close_position(TOKEN_ID)
print(tx)

**Comment by ulrickpsp** [comment]
Having same issue in Goerli

**Comment by ulrickpsp** [comment]
I guess it is related to the http provider you are using. I was using ANKR and this method is not available from this provider. You may use another provider or set up your own node.

**Comment by avasque2** [comment]
Thanks @ulrickpsp I think you're right. I tried a raw transaction and similar issues.

**Comment by ricardbou** [comment]
I have found the same problem when doing uniswap.mint_liquidity(...):
  "ValueError: {'code': -32601, 'message': 'The method eth_sendTransaction does not exist/is not available'}"

I use INFURA too.

I have found that the problem is that the transaction is not being signed:
https://stackoverflow.com/questions/68236469/error-returned-error-the-method-eth-sendtransaction-does-not-exist

Please help !! Thanks !!

**Comment by ililic** [comment]
Fyi @avasque2 you've exposed your INFURA project key which is meant to be kept secret. Recommend deleting that key and updating the post ;-)

**Comment by avasque2** [comment]
> Fyi @avasque2 you've exposed your INFURA project key which is meant to be kept secret. Recommend deleting that key and updating the post ;-)

Thanks @ililic

**Comment by ililic** [comment]
By the way, for the `eth_sendTransaction` issue:

Optimism doesn't support it (https://community.optimism.io/docs/developers/build/json-rpc/#eth-sendtransaction). 

To work around it, you can use the sign_and_send_raw_middleware: https://web3py.readthedocs.io/en/v5/middleware.html#signing something like:

```
w3 = web3.Web3(web3.HTTPProvider(provider))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)
w3.middleware_onion.add(construct_sign_and_send_raw_middleware(private_key))
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, web3= w3)
```

The `eth_feeHistory` issue is the one I'm currently stuck on…

**Comment by avasque2** [comment]
Ah ok, bummer. Thanks for the work around!
