### ISSUE TITLE
 Is it necessary to add v2 support for add_liquidity?

### ISSUE THREAD

**Issue by yangmingming** [uniswap-python/uniswap-python#313]
[Liquidity Methods (v1 only)](https://uniswap-python.com/getting-started.html#id12)
```
# Add liquidity to the pool.
uniswap.add_liquidity(bat, 1*10**18)

# Remove liquidity from the pool.
uniswap.remove_liquidity(bat, 1*10**18)
```

If I use v1, many functions to obtain the swap amount cannot be used.

Moreover, if you add liquidity, do you need to specify two kinds of coins? Give users more options.

Thank you!

**Comment by ErikBjare** [comment]
There is no good reason to use v1. It has practically no usage or liquidity.

>Moreover, if you add liquidity, do you need to specify two kinds of coins?

Not in v1. Everything was traded against ETH.
