### ISSUE TITLE
get_price_input execution reverted

### ISSUE THREAD

**Issue by Mattiatore** [uniswap-python/uniswap-python#315]
I am calling the get_price_input function on the manifold finance token (ETH contract at '0xd084944d3c05cd115c09d072b9f44ba3e0e45921'), checking on the UI there is a pool containing this token in v3.
I call the function this way:

<img width="798" alt="Screenshot 2023-01-29 at 10 11 43" src="https://user-images.githubusercontent.com/47110871/215316617-67c64162-0b12-48fe-bb38-4ecb2cf2284f.png">

Although I am getting this error:
<img width="977" alt="Screenshot 2023-01-29 at 10 13 39" src="https://user-images.githubusercontent.com/47110871/215316708-506be519-271a-4fd9-8e28-beab0d6be4e5.png">

**Comment by ErikBjare** [comment]
There is no FOLD/ETH pool at the default fee tier of 0.3%: https://info.uniswap.org/#/tokens/0xd084944d3c05cd115c09d072b9f44ba3e0e45921

If you specify `fee=1000`, it should work.

**Comment by Mattiatore** [comment]
For `fee=10000` it works, thanks. Just to check if the behaviour is expected, when I use for this query dai as output token I still get the same error, even with the correct fee value, using eth as output works instead.

**Comment by ErikBjare** [comment]
Again, this is probably due to there not being a pool for the (token1, token2, fee) combination (there is no DAI/FOLD pool). You can check https://info.uniswap.org to look up pools.
