### ISSUE TITLE
'Web3' has no attribute 'toChecksumAddress'. Did you mean: 'to_checksum_address'?

### ISSUE THREAD

**Issue by viponedream** [uniswap-python/uniswap-python#327]
AttributeError: type object 'Web3' has no attribute 'toChecksumAddress'. Did you mean: 'to_checksum_address'?

can not run in with new web3

**Comment by Shaun-Yao** [comment]
I am using web3py v6.20.3, uniswap-python v0.7.1 , still have the same issue

**Comment by ErikBjare** [comment]
@Shaun-Yao There are no references to `toChecksumAddress` (except in an example...) since v0.7.0: https://github.com/search?q=repo%3Auniswap-python%2Funiswap-python%20toChecksumAddress&type=code

Show us the stacktrace.

**Comment by Shaun-Yao** [comment]
> @Shaun-Yao There are no references to `toChecksumAddress` (except in an example...) since v0.7.0: https://github.com/search?q=repo%3Auniswap-python%2Funiswap-python%20toChecksumAddress&type=code
> 
> Show us the stacktrace.

Sorry, its not ur issue, its the old version of web3.
