### ISSUE TITLE
fail to use mint_liquidity

### ISSUE THREAD

**Issue by mostar** [uniswap-python/uniswap-python#328]
Hello I fail to use mint_liquidity the error is: 
error web3.exceptions.ContractLogicError: execution reverted: STF

both coins pass the approve transactions.

```
poolContarctObject = uniswap.get_pool_instance(weth,uni,3000)
tx = uniswap.mint_liquidity(poolContarctObject, 1999999999999999855, 13709415843592873, -50760, -47440, 18446744073709551616)
print(tx)

```
Not sure the ration amount_0, amount_1 is fine
I allow try singel side liqudiry and fail (amount_0 or amount_1 is 0 and tick_lower and tick_upper below or above market price).
How to debug it?

> Traceback (most recent call last):
>   File "/app/test.py", line 107, in <module>
>     tx = uniswap.mint_liquidity(poolContarctObject, 1999999999999999855, 13709415843592873, -50760, -47440, 18446744073709551616)
>   File "/usr/local/lib/python3.9/site-packages/uniswap/decorators.py", line 65, in check_version
>     return f(self, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/uniswap/uniswap.py", line 1156, in mint_liquidity
>     tx_hash = nft_manager.functions.mint(
>   File "/usr/local/lib/python3.9/site-packages/web3/contract/contract.py", line 479, in transact
>     return transact_with_contract_function(
>   File "/usr/local/lib/python3.9/site-packages/web3/contract/utils.py", line 172, in transact_with_contract_function
>     txn_hash = w3.eth.send_transaction(transact_transaction)
>   File "/usr/local/lib/python3.9/site-packages/web3/eth/eth.py", line 362, in send_transaction
>     return self._send_transaction(transaction)
>   File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 68, in caller
>     result = w3.manager.request_blocking(
>   File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 231, in request_blocking
>     response = self._make_request(method, params)
>   File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 175, in _make_request
>     return request_func(method, params)
>   File "/usr/local/lib/python3.9/site-packages/web3/middleware/signing.py", line 161, in middleware
>     transaction = format_and_fill_tx(params[0])
>   File "cytoolz/functoolz.pyx", line 504, in cytoolz.functoolz.Compose.__call__
>   File "cytoolz/functoolz.pyx", line 249, in cytoolz.functoolz.curry.__call__
>   File "/usr/local/lib/python3.9/site-packages/web3/_utils/transactions.py", line 132, in fill_transaction_defaults
>     default_val = default_getter(w3, transaction)
>   File "/usr/local/lib/python3.9/site-packages/web3/_utils/transactions.py", line 72, in <lambda>
>     "gas": lambda w3, tx: w3.eth.estimate_gas(tx),
>   File "/usr/local/lib/python3.9/site-packages/web3/eth/eth.py", line 292, in estimate_gas
>     return self._estimate_gas(transaction, block_identifier)
>   File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 68, in caller
>     result = w3.manager.request_blocking(
>   File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 232, in request_blocking
>     return self.formatted_response(
>   File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 197, in formatted_response
>     apply_error_formatters(error_formatters, response)
>   File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 73, in apply_error_formatters
>     formatted_resp = pipe(response, error_formatters)
>   File "cytoolz/functoolz.pyx", line 666, in cytoolz.functoolz.pipe
>   File "cytoolz/functoolz.pyx", line 641, in cytoolz.functoolz.c_pipe
>   File "/usr/local/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 762, in raise_contract_logic_error_on_revert
>     raise ContractLogicError(response["error"]["message"])
> web3.exceptions.ContractLogicError: execution reverted: STF
>

**Comment by ehart004** [comment]
I had some trouble with the mint calls reverting as well. I noticed that there were some FIXME comments there and some possible ideas on what was going wrong. Does anyone happen to be looking into this or have any suggestions?  Thanks.

**Comment by mostar** [comment]
It was gas issue, see trace:

> File "/usr/local/lib/python3.9/site-packages/web3/eth/eth.py", line 292, in estimate_gas
> return self._estimate_gas(transaction, block_identifier)
