### ISSUE TITLE
domain uniswap-python.com is not resolving 

### ISSUE THREAD

**Issue by dubstard** [uniswap-python/uniswap-python#345]
**Describe the bug**
uniswap-python.com does not resolve

![image](https://github.com/uniswap-python/uniswap-python/assets/49607867/f840baf5-f730-449e-ac7f-c51d558f306e)
![image](https://github.com/uniswap-python/uniswap-python/assets/49607867/2c237b03-fda0-435b-b733-fd6a2ad8b046)

https://isitup.org/uniswap-python.com
last issued SSL is from 1 year ago
https://crt.sh/?id=10197655960
**To Reproduce**
Open web browser and navigate to uniswap-python.com

**Expected behavior**
Open website

**Additional context**
Possibly copycats / imitators / phishing / cybers squatters etc
```
uniswappython.com
uniswappython.org
uniswap-python.org
```

**Comment by ErikBjare** [comment]
Strange. The site is hosted on GitHub pages. I will check the domain registration.

**Comment by ErikBjare** [comment]
Actually... I might not have it.

@shanefontaine did you register the domain?

**Comment by shanefontaine** [comment]
@dubstard @ErikBjare this has been resolved. I apologize for the outage.

**Comment by dubstard** [comment]
Thanks!
