### ISSUE TITLE
How can i get history statistic?

### ISSUE THREAD

**Issue by jin-cheng-87** [uniswap-python/uniswap-python#352]
Hi,there;
can i get some history statistics from this SDK such as All Pools、TVL,、Volume 24H、Volume 7D, Total Tokens Locked、24h Fees and so on……
thanks so much;

**Comment by ErikBjare** [comment]
Do some research before you ask. Most of what you're requesting isn't offered.

**Comment by jin-cheng-87** [comment]
i thinks many other people need these history statistics in the same way,
So will you provide these API in the future? 
thanks;

**Comment by ErikBjare** [comment]
This library is not a suitable way to get those stats.

The answer is no.
