### ISSUE TITLE
uniswap.make_trade_output() - Arguments Type

### ISSUE THREAD

**Issue by Odelf18** [uniswap-python/uniswap-python#354]
**Describe the bug**
In the uniswap.make_trade_output() function, qty is expected to be an integer (int), but the function actually receives a floating-point number (float). This issue arises when calling the function with an amount less than 1 ETH.

**To Reproduce**
Follow the doc 
`uniswap.make_trade_output(bat, eth, 1*10**18)  # buy BAT for 1 ETH`

**Expected behavior**
Convert qty to an integer to ensure compatibility with the function's expected parameter type.

**Additional context**
This issue seems to occur specifically when dealing with amounts lower than 1 ETH. Please note that the suggested fix involves converting qty to an integer using the int() function before calling the make_trade_output() function. However, consider whether this conversion to an integer is appropriate for your specific use case, as it may affect the precision of calculations involving fractional amounts.

**Comment by ErikBjare** [comment]
This is not a bug.

`1*10**18` is an int. If you want less than one ETH, you can't just do `0.5*10**18`, and you shouldn't `int()` it, instead do `5*10**17`. This does not affect precision.

A typechecker like mypy would have warned you about passing floats.
