### ISSUE TITLE
How to fetch or calculate price of an asset?

### ISSUE THREAD

**Issue by RoscoeTheDog** [uniswap-python/uniswap-python#362]
I apologize for some lack of knowledge with MM pools in advance. I understand some broad general concepts since I've used the front end swap feature a lot but the core underlying relationships I'm super unfamiliar with. 

I've made a little bot that supposed to automatically buy BNB from USDT when it falls below a USD threshold, which means I need to calculate the value of spot BNB in my wallet-- in terms of USD value. 

I scrubbed through some github questions and found a supposed solution from #319. @qraxiss posted the below code. When I run it no values are printed or returned. After performing some debugging, I can see that `prices` in the line ` prices = [perm[0] + perm[1] for perm in permutations(self.pool_prices('different'), 2)] + self.pool_prices('single')` is returning an empty array. Nothing was changed, besides including a BNB RPC node source which is requried.

So a few questions are:
1) how to get or calculate an asset price in USD terms (preferably USD and not a stablecoin)
2) how can @qraxiss script be modified to return relevant data
3) is there a better way to do this?

From what I've taken away from this is that you have to simulate a swap between BNB and a stablecoin like USDT to determine the BNB price. However, this means if USDT failed or USDC failed you could have unexpected behavior in your trading bots. You can take an aggregate of all stablecoin pairs but I feel there is a more thought-out approach to this issue.

<br>
<br>
<br>
Quote:
<br>
<br>

My solution is here. +- 1 in 1000 margin of error.

If a PR is requested, I can write a more professional one. But for me this is enough.

```python
from concurrent.futures import ThreadPoolExecutor
from collections import defaultdict
from itertools import permutations
from uniswap import Uniswap
from web3 import Web3


class Token:
    def __init__(self, address, name, symbol, decimals) -> None:
        self.address = Web3.toChecksumAddress(address)
        self._raw_address = address
        self.name = name
        self.symbol = symbol
        self.decimals = decimals
        self.qty = 10 ** self.decimals


class UniswapPrice:
    sides = {
        'sell': 'get_price_output',
        'buy': 'get_price_input'
    }

    percentages = [50, 100]
    fees = [100, 300, 3000, 10000]

    def __init__(self, v2, v3):
        self.swap = {
            'v2': {
                'exchange': v2,
                'percentages': self.percentages,
                'fees': [3000]
            },
            'v3': {
                'exchange': v3,
                'percentages': self.percentages,
                'fees': self.fees
            }
        }

    def find_best(self):
        prices = [perm[0] + perm[1] for perm in permutations(
            self.pool_prices('different'), 2)] + self.pool_prices('single')
        if len(prices) == 0:
            return
        if self.side == 'sell':
            return min(prices)
        elif self.side == 'buy':
            return max(prices)

    def get_price(self, exchange, fee, qty):
        queue = [self.t0.address, self.t1.address] if self.side == 'buy' else [
            self.t1.address, self.t0.address]
        price_func = getattr(exchange, self.sides[self.side])
        return price_func(*queue, qty, fee=fee) / self.t1.qty

    def pool_prices(self, price_type):
        if price_type == 'single':
            perc = 100
        elif price_type == 'different':
            perc = 50

        return [
            fee[perc]
            for exchanges in self.futures.values()
            for fee in exchanges.values()
            if isinstance(fee[perc], float)
        ]

    def get_best_price(self, t0, t1, side):
        self.t0 = t0
        self.t1 = t1
        self.side = side

        self.get_prices()
        return self.find_best()

    def get_prices(self):
        self.futures = defaultdict(dict)

        with ThreadPoolExecutor(max_workers=10) as executor:
            for exchange_name, exchange_data in self.swap.items():
                self.futures[exchange_name] = defaultdict(dict)
                for fee in exchange_data['fees']:
                    self.futures[exchange_name][fee] = defaultdict(dict)
                    for percentage in exchange_data['percentages']:
                        self.futures[exchange_name][fee][percentage] = defaultdict(
                            dict)
                        qty = self.t0.qty * percentage // 100
                        self.futures[exchange_name][fee][percentage] = executor.submit(
                            self.get_price, exchange_data['exchange'], fee, qty
                        )

            for exchange_name, exchange_fees in self.futures.items():
                self.futures[exchange_name] = dict(exchange_fees)
                for fee, percentage_data in exchange_fees.items():
                    self.futures[exchange_name][fee] = dict(percentage_data)
                    for percentage, future in percentage_data.items():
                        try:
                            self.futures[exchange_name][fee][percentage] = future.result(
                            )
                        except:
                            pass


web3 = Web3(Web3.HTTPProvider("YOUR-JSON-RPC-URL"))

uni_v2 = Uniswap(
    address=None,
    private_key=None,
    version=2,
    web3=web3
)

uni_v3 = Uniswap(
    address=None,
    private_key=None,
    version=3,
    web3=web3
)

t0 = Token(**{
               "symbol": "ETH",
               "name": "Wrapped Ethereum",
               "decimals": 18,
               "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
           }
)


t1 = Token(**{
               "symbol": "WBTC",
               "name": "Wrapped Bitcoin",
               "decimals": 8,
               "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
           }
)


price_calculator = UniswapPrice(uni_v2, uni_v3)

print(price_calculator.get_best_price(t0, t1, 'buy'),
      price_calculator.get_best_price(t0, t1, 'sell'))
```

_Originally posted by @qraxiss in https://github.com/uniswap-python/uniswap-python/issues/319#issuecomment-1464682032_

**Comment by RoscoeTheDog** [comment]
As an update: I realized that gas amounts have nothing to do with USD value, so I'm implementing the bot just to use spot amounts and thresholds.

But this question remains valid. How would you simulate a trade with BTC/USDT without on chain execution? I believe I heard something about doing that elsewhere...

**Comment by RoscoeTheDog** [comment]
I resolved my issue. I think when trying this in the past I had an incorrect type, such as `qty` not being casted to int or some other issue. Swear I tried it before 😅 

If this function returns the amount out for the amount in, with `qty` being in ether units of 10**18, then you simplify specify `1 * 10**18` to return the trade rate. If you want it relative to USD, then target a stablecoin.
```python
# estimate tokens out from amount in
price_usd = self.quickswap.get_price_input(token_in, token_out, 1 * 10**18) # assuming token_out is a stablecoin.
token_out_estimate = self.quickswap.get_price_input(token_in, token_out, int(qty))
```

**Comment by qraxiss** [comment]
You cant calculate official pair price with uniswap-python library. Because uniswap v3 have lot of pair pools. And we dont know which pool is better price. U have to check prices on every pool.

**Comment by RoscoeTheDog** [comment]
> You cant calculate official pair price with uniswap-python library. Because uniswap v3 have lot of pair pools. And we dont know which pool is better price. U have to check prices on every pool.

When you say "you have to check prices on every pool", do you mean only for V3? My solution above seemed to work as intended. I'm currently using only V2 because V3 had issues initializing but I might come back to it.

Could I see an example of how to check prices for a swap on V3? I feel like there should be a helper function that takes care of this in the library already. `get_price_input`?
