### ISSUE TITLE
Add support for swapExactTokensForTokensSupportingFeeOnTransferTokens

### ISSUE THREAD

**Issue by CryptoGnome** [uniswap-python/uniswap-python#40]
There is  newer function for tokens that have Fee on Transfer that is causing issues on some transfers, could you please take a look to have a sanctity check [tokenin or tokenout] have this function in the abi to use the correct transfer method to prevent failed TX's

https://uniswap.org/docs/v2/smart-contracts/router02/#swapexacttokensfortokenssupportingfeeontransfertokens
function swapExactTokensForTokensSupportingFeeOnTransferTokens(
  uint amountIn,
  uint amountOutMin,
  address[] calldata path,
  address to,
  uint deadline
) external;

Thanks for keeping this project alive and well!

**Comment by ErikBjare** [comment]
Huh, that's interesting. Could you give an example of such a token? (I guess BOMB would be an example?) 

I probably don't have time to implement a fix, but I'd gladly review a PR if you're up for it. Shouldn't be too hard to fix.

**Comment by CryptoGnome** [comment]
CORE , there are tons like it popping up now
