### ISSUE TITLE
Overly eager to approve tokens

### ISSUE THREAD

**Issue by albertocastillo2001** [uniswap-python/uniswap-python#73]
Hello

Just tried to execute a trade with eth to a token using make_trade

For some reason, it attempted to approve the token before. I would like to omit this behavior, and approve the token later.
Also, for some reason it also tried to approve it even when it was already approved.

Thank you.

**Comment by ErikBjare** [comment]
It needs to approve the token if you are going to trade with it, you can't do it after the trade.

**Comment by albertocastillo2001** [comment]
Well, but the thing is that it seems to approve it before trading back. Let me explain

if I want to swap eth for a token (I tried CVP), it tried to approve CVP before swapping eth for CVP. Normally when you trade with Uniswap you do like this:

Swap eth for the token
Approve
Swap token for eth.

So I don't understand why it tried to approve it even before swapping eth for the token.

Thanks

**Comment by albertocastillo2001** [comment]
> It needs to approve the token if you are going to trade with it, you can't do it after the trade. If you read the code you can find the approval condition which is checked.
> 
> If it tries to approve the token again, that's probably because the previous transaction hadn't gone through yet (or for whatever reason your node wasn't aware of it yet) and maybe you had restarted your program so it wasn't aware of the pending TX.

Is it possible to reopen this? Thanks

**Comment by ErikBjare** [comment]
Ah, yeah you're right that might not be necessary. If so, we welcome a PR with a fix.

**Comment by albertocastillo2001** [comment]
Thanks. Keep in mind that for the most part you might not be interested to approve, or you might want to approve manually. So either a parameter on the make trade function to optionally approve

If you want to trade fast, you're interested on swapping eth for the token, then approving, then swap back. Not to approve first.

**Comment by yazpower** [comment]
Hi I think I have the same problem
I want to make at trade and each time it try to approve the token (but the token is already approved)

the problem come from this function
def call_contract_function
when it call in the try/catch
        output_data = web3.codec.decode_abi(output_types, return_data)
this should be an ABI problem
I

![image](https://user-images.githubusercontent.com/13495284/114955298-ad80a080-9e5c-11eb-8ba0-d43e912dd5b8.png)


[main.txt](https://github.com/shanefontaine/uniswap-python/files/6321735/main.txt)



Traceback (most recent call last):
  File "/home/yaz/dev/defi/uniswap/pyton/uniswap_tuto.py", line 76, in <module>
    swap(token_uni, token_dai, 0.1)
  File "/home/yaz/dev/defi/uniswap/pyton/uniswap_tuto.py", line 68, in swap
    uniswap_wrapper.make_trade(token_input, token_output, value * 10 ** 18)  # calls _eth_to_token_input
  File "/usr/local/lib/python3.7/dist-packages/uniswap/uniswap.py", line 69, in approved
    is_approved = self._is_approved(token_two)
  File "/usr/local/lib/python3.7/dist-packages/uniswap/uniswap.py", line 737, in _is_approved
    .functions.allowance(self.address, contract_addr)
  File "/usr/local/lib/python3.7/dist-packages/web3/contract.py", line 964, in call
    **self.kwargs
  File "/usr/local/lib/python3.7/dist-packages/web3/contract.py", line 1528, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

Process finished with exit code 1

**Comment by MrSp4nky** [comment]
Any updates on this?

**Comment by ErikBjare** [comment]
@MrSp4nky No, PRs appreciated.

**Comment by jornx** [comment]
Running into this problem aswell, makes fast trades really hard
