### ISSUE TITLE
get pair price

### ISSUE THREAD

**Issue by dustiwe** [uniswap-python/uniswap-python#78]
I try to get the price of a pair per unit, but the prices always differ with the web application, but sometimes, on rare occasions, they coincide.
Code:
`from uniswap import Uniswap
from web3 import Web3
address = "0x0000000000000000000000000000000000000000" # or "0x0000000000000000000000000000000000000000", if you're not making transactions
private_key = 'None'  # or None, if you're not going to make transactions
w3 = Web3(Web3.HTTPProvider('https://mainnet.infura.io/v3/<your key>'))
uniswap_wrapper = Uniswap(address, private_key, version=2,web3=w3,max_slippage=1)  # pass version=2 to use Uniswap v2
def conversion(rate, usd_rate, decimal):
    conversion = ((1 / rate) * (usd_rate / 10 ** 6)) * decimal
    return round(conversion,4)
def dep(a,de):
    usdt = w3.toChecksumAddress("0xdac17f958d2ee523a2206206994597c13d831ec7")
    usdt_rate = uniswap_wrapper.get_token_eth_output_price(usdt, 10 ** 18)
    poolz = w3.toChecksumAddress(a)
    poolz_rate = uniswap_wrapper.get_eth_token_input_price(poolz, 10 ** 18)
    print("dep=", conversion(poolz_rate, usdt_rate, 10 ** de), "USDT")

def withdraw(b,de):
    usdt = w3.toChecksumAddress("0xdac17f958d2ee523a2206206994597c13d831ec7")
    usdt_rate = uniswap_wrapper.get_eth_token_input_price(usdt, 10 ** 18)
    poolz = w3.toChecksumAddress(b)
    poolz_rate = uniswap_wrapper.get_token_eth_output_price(poolz, 10 ** 18)
    print("withdraw=", conversion(poolz_rate, usdt_rate, 10 ** de), "USDT")

dep('0x8a6f3bf52a26a21531514e23016eeae8ba7e7018',8)
withdraw('0x8a6f3bf52a26a21531514e23016eeae8ba7e7018',8)`

![Screenshot_7](https://user-images.githubusercontent.com/65848440/112044925-ee81df80-8b52-11eb-8258-bc1cf9f0c550.png)
![Screenshot_8](https://user-images.githubusercontent.com/65848440/112044927-ef1a7600-8b52-11eb-908c-ffdd56e66448.png)
![Screenshot_9](https://user-images.githubusercontent.com/65848440/112044928-efb30c80-8b52-11eb-9a44-0e9b89355994.png)

get_eth_token_input_price
get_token_eth_input_price
get_eth_token_output_price
get_token_eth_output_price
I tried all combinations of these methods, the price is different by 0.03% or 4%
The pair has plenty of liquidity

**Comment by ErikBjare** [comment]
Probably because of the bad assumed route, see #69.

**Comment by dustiwe** [comment]
And what should I do please tell me?

> Probably because of the bad assumed route, see #69.

**Comment by ErikBjare** [comment]
You can implement the feature request I linked, there is no quick solution.

**Comment by brent-virgox** [comment]
i tried the same token pair on v3, with qty=100 (and a few other qty choices). Got a ContractLogicError: execution reverted when calling quoteExactInputSingle. Anyone has the same issue?

**Comment by dustiwe** [comment]
> i tried the same token pair on v3, with qty=100 (and a few other qty choices). Got a ContractLogicError: execution reverted when calling quoteExactInputSingle. Anyone has the same issue?

I don't know what your problem is, but use 0x api
