### ISSUE TITLE
CI tests fail in PRs

### ISSUE THREAD

**Issue by ErikBjare** [uniswap-python/uniswap-python#88]
I haven't looked into it, but it seems to be a recurring issue.

**Comment by ErikBjare** [comment]
In #58 I ran the tests locally, and they passed. 

Not sure why they failed in the PR, perhaps due to the Infura token being kept secret? The PR is merged now anyway, we'll see if the tests pass on master.

**Comment by ErikBjare** [comment]
Having issues again with token -> token swaps in `test_make_trade`:

```
FAILED tests/test_uniswap.py::TestUniswap::test_make_trade[1-0x6B175474E89094C44Da98b954EedeAC495271d0F-0x0D8775F648430679A709E98d2b0Cb6250d2887EF-1000000000-None-does_not_raise]
```

The error:

```
Runtime Error: invalid JUMP at 72e826e5ec1e970f37af4b41635535232c58bcb7795871b2738347fd8c1314ca/2a1530c4c41db0b0b2bb646cb5eb1a67b7158667:39
```

I thought I fixed that in #58, but apparently not for good.

**Comment by ErikBjare** [comment]
Ah damn, just realized that's for v1... Explains a lot.

**Comment by ErikBjare** [comment]
Wasted way too much time on this today. Considering just dropping support for v1 as it's pretty dead anyway.

What do you think @shanefontaine?

**Comment by shanefontaine** [comment]
I am for dropping V1 support. Looks like V1 [only has 330](https://v1.uniswap.info/) transactions in the last 24 hours and decreasing daily volume -- not enough to warrant ongoing support, IMO.

**Comment by ErikBjare** [comment]
I fixed the remaining failing tests for v1 in https://github.com/uniswap-python/uniswap-python/commit/f782df595184fad04cb5ef3570f6f6b58cf344aa. Might keep support around for another version or so.

The issue in https://github.com/uniswap-python/uniswap-python/issues/88#issuecomment-832574529 turns out to have been caused by there not being 1000 ETH in the pool from which the `InsufficientFunds` test tried to buy 1000 ETH with DAI :man_facepalming:

**Comment by ErikBjare** [comment]
Things seem to work fine now, closing.
